import type { Metadata } from 'next';
import styles from '../app/globals.module.scss';

export const metadata: Metadata = {
  title: 'Domain-market',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={styles.Main}>{children}</body>
    </html>
  );
}
