import type { Metadata } from 'next';
import styles from '../app/globals.module.scss';
import { CartProvider } from './components/cart/cart';
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'Domain-market',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartProvider>
      <html lang='en'>
        {/* <Head>
          <meta name='viewport' content='width=device-width, initial-scale=1' />
        </Head> */}
        <body className={styles.Main}>{children}</body>
      </html>
    </CartProvider>
  );
}
